packaging_format = 2

id = "automad"
name = "Automad"
description.en = "Flat-file content management system and template engine"
description.fr = "Système de gestion de contenu de fichiers plats et un moteur de modèles"

version = "2.0.0-beta.54~ynh7"

maintainers = []

[upstream]
license = "MIT"
website = "https://automad.org/"
admindoc = "https://automad.org/getting-started"
userdoc = "https://automad.org/user-guide"
code = "https://github.com/marcantondahmen/automad"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/automad"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.user]
    type = "user"
    ask.en = "Please chose the first user :"
    ask.fr = "Choisissez le premier utilisateur :"

    [install.password]
    ask.en = "Please chose a password for the first user :"
    ask.fr = "Choisissez un mot de passe :"
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/automadcms/automad-dist/archive/refs/tags/2.0.0-beta.54.tar.gz"
        sha256 = "6b57dabd991225f5655bfd70b99601a509d72ccc7ab14e879e2ab4fcafb98d0a"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.5-gd, php8.5-zip, php8.5-curl"
