packaging_format = 2

id = "automad"
name = "Automad"
description.en = "Flat-file content management system and template engine"
description.fr = "Système de gestion de contenu de fichiers plats et un moteur de modèles"

version = "1.10.9~ynh4"

maintainers = []

[upstream]
license = "MIT"
website = "https://automad.org/"
admindoc = "https://automad.org/getting-started"
userdoc = "https://automad.org/user-guide"
code = "https://github.com/marcantondahmen/automad"

[integration]
yunohost = ">= 11.1.18"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/automad"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/marcantondahmen/automad/archive/refs/tags/1.10.9.tar.gz"
        sha256 = "d60266a2e7b4f433cf0484583dfd933c9facfbd09ab79c6db5897e9b8abe996b"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.0-gd php8.0-zip php8.0-curl"
