#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# SETUP FIRST USER
#=================================================
ynh_script_progression "Setting up the first user..."

user_info=$(ynh_exec_as_app php${php_version} $install_dir/automad/console createuser)
user_name=$(echo "$user_info" | grep "Name:")
user_pass=$(echo "$user_info" | grep "Password:")

ynh_app_setting_set --key=user_name --value=$user_name
ynh_app_setting_set --key=user_pass --value=$user_pass

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
